### PR TITLE
fix: file list overflow

### LINKED ISSUE #360: [Issue Report] Text overflows if file name is too long
image

A solution would be to set overflow: hidden on the <td>s. Fade out gradient would be stylistically nice

### LINKED ISSUE #361: [Issue Report] last<tr> overflows the table
Last row in the table is not completely visible

**Steps to reproduce**

1. Run the executable in a directory with a lot of files in it.
2. Open the link
3. Notice that the last item is not completely visible

**Environment**

HTTP Server Version: v0.8.6
Operative System: Windows

**Screenshots**

image
Notice that I completely scrolled down

https://github.com/http-server-rs/http-server/assets/71790328/bb120ba3-f1d8-4090-ad51-4ff43a283c19

Website Snapshot: https://mega.nz/file/J8cwSSyA#8ioa2D-nT8pyi_xn9lowMXP_WtPGR5NgrmHAJSwGam0

### PR DESCRIPTION
**Pull request by Antosser**
With these changes
* Table cell will not overflow 
image
* Status bar will not cover up the table behind itself
image

### CODE REVIEW

**Comment by Antosser** [comment]
#360 #361

**Review by LeoBorai — APPROVED** [review]
LGTM! Thanks!

**Comment by LeoBorai** [comment]
@Antosser con you please run `cargo clippy --fix`?

**Comment by Antosser** [comment]
I didn't introduce any of those clippy warnings but aight

**Comment by Antosser** [comment]
> @Antosser con you please run `cargo clippy --fix`?

I have done it, but I don't understand why this would belong into this pull request. Modifying the same files in multiple pull requests can lead to merge conflicts. Besides, this issue has nothing to do with the pull request

**Review by LeoBorai — APPROVED** [review]

**Pull request merged**
